# Spring Boot application.yaml for MySQL database
spring:
    datasource:
        url: ${JDBC_URL:jdbc:mysql://localhost:3306/weather_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
        username: ${MYSQL_USER:root}
        password: ${MYSQL_PASSWORD:}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:default}

server:
    port: ${SERVER_PORT:8080}
    servlet:
        context-path: ${SERVER_CONTEXT_PATH:/}

logging:
    level:
        root: INFO
        org.springframework.web: DEBUG
        org.hibernate: ERROR

# JWT Configuration
app:
    jwt:
        secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLong}
        expirationMs: ${JWT_EXPIRATION_MS:86400000} # 24 hours
